server:
  port: HTTP_SERVER_PORT

infobip.remoting:

  server:
    autostart: RMI_AUTO_START
    properties:
      http:
        rmi.remoting.endpoint: http://SERVER_NAME:HTTP_SERVER_PORT/rmi

      mml:
        server:
          port: MML_SERVER_PORT
          shell.port: MML_SERVER_SHELL_PORT